name: Build MAUI Apps

on:
    push:
        branches:
            - "release/*"

jobs:
    build:
        runs-on: macos-14

        env:
            BUILD_TIMESTAMP: ${{ github.run_id }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.100"

            - name: Install MAUI workloads
              run: |
                  dotnet workload install maui
                  dotnet workload install maui-android
                  dotnet workload install maui-ios
                  
            - name: Run GitVersion
              uses: gittools/actions/gitversion/execute@v0

            - name: Build all apps
              run: |
                  mkdir -p build-${BUILD_TIMESTAMP}
                  # ClassLibrary and TemplateProject are excluded by omitting them from this list
                  apps=("ClientC" "ClientD" "ClientE")

                  for app in "${apps[@]}"; do
                    echo "Building $app"
                    
                    echo "Restore"
                    dotnet restore $app

                    # Android
                    echo "Building Android APK..."
                    mkdir -p build-${BUILD_TIMESTAMP}/${app}/Android
                    # Versions are now handled by GitVersion.MsBuild
                    dotnet publish $app -f net9.0-android -c Debug -p:AndroidPackageFormat=apk
                    cp $app/bin/**/net9.0-android/**/*.apk build-${BUILD_TIMESTAMP}/${app}/Android/ || true

                  done

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ env.BUILD_TIMESTAMP }}
                  path: build-${{ env.BUILD_TIMESTAMP }}
# iOS IPA
# echo "Building iOS IPA..."
# mkdir -p build-${BUILD_TIMESTAMP}/${app}/iOS
# dotnet build $app -f:net10.0-ios -c Release -p:Platform=iPhone -p:BuildIpa=true \
#     -p:SigningKeychain=login.keychain \
#     -p:AutomaticSigning=true
# cp $app/bin/Release/net10.0-ios/*.ipa build-${BUILD_TIMESTAMP}/${app}/iOS/ || true
